# Generated by Django 2.1.15 on 2021-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210306_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gamer',
            field=models.BooleanField(default=False),
        ),
    ]
