# Generated by Django 2.1.15 on 2021-03-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreline',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorelines', to='core.Game'),
        ),
        migrations.AlterField(
            model_name='scoreline',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorelines', to='core.Tournament'),
        ),
    ]
