# Generated by Django 2.2.24 on 2021-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210308_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreline',
            name='first_player_score_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreline',
            name='second_player_score_goals',
            field=models.IntegerField(default=0),
        ),
    ]
